version: '3.3'

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./storage:/app/storage

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  storage: 
  prometheus_data: